#spring:
#    datasource:
#        driver-class-name: oracle.jdbc.OracleDriver
#        url: jdbc:oracle:thin:@localhost:1521:orcl
#        username: SCOTT
#        password: dbswls0803
#
#mybatis:
#    mapper-locations: classpath:/mapper/*.xml
#    type-aliases-package: thekary.jwt_study.dto

jwt:
    header: Authorization
    secret_key: 6rWJ7J6l7Z6I7Ja066Ck7Jq07Jqw66asand07Lmc6rWs #????????jwt??
    expire_time: 86400 #24??.



